List<Map<String, String>> mbti_qs = [
  {
    'order': '1',
    'question': 'It’s 10:50 p.m. You need to use Washine machine Today. Because You have no towel!',
    'image': "asset/images/la.png",
    'ans_a': 'Using washing Machine Anyway',
    'ans_b': 'No. Let’s Do it Tomorrow!',
  },
  {
    'order': '2',
    'question': 'It\'s annoying to keep bringing the shower basket to the shower room..',
    'image': "asset/images/shower.png",
    'ans_a': 'I\'ll just leave the shower basket and hairdryer in the cabinet.',
    'ans_b': 'Still, I have to carry it! Just keep carrying it.',
  },
  {
    'order': '3',
    'question': 'The toilet water doesn\'t flush well.. Should I give up?',
    'image': 'asset/images/toilet.png',
    'ans_a': 'I\'ll try various angles to flush the toilet water vigorously, and if it still doesn\'t work, I\'ll contact maintenance!',
    'ans_b': 'I don\'t know, I guess I should give up on this toilet. Someone else will flush it down.',
  },
  {
    'order': '4',
    'question': 'I have to apply for overnight stay permission! The current time is 10:55 PM!',
    'image': 'asset/images/why.png',
    'ans_a': 'I\'ll apply for overnight stay permission differently and faster than others.',
    'ans_b': 'Hehe, I don\'t know. Let\'s just have fun! We can apply until midnight anyway.',
  },
  {
    'order': '5',
    'question': 'I brought delicious side dishes from my mother, but they don\'t all fit in the refrigerator!',
    'image': 'asset/images/re.png',
    'ans_a': 'I\'ll prepare a bigger container for my portion in the refrigerator.',
    'ans_b': 'Utilize the communal refrigerator space.',
  },
  {
    'order': '6',
    'question': 'It\'s too cold...',
    'image': 'asset/images/cold.png',
    'ans_a': 'Electric heating pads are the best. I need at least one.',
    'ans_b': 'Put on some clothes! It\'s too cold!',
  },
  {
    'order': '7',
    'question': 'I\'m craving nicotine..',
    'image': 'asset/images/ni.png',
    'ans_a': 'Using an e-cigarette should be fine~ I\'ll have one in the bathroom~',
    'ans_b': 'I\'ll go to the smoking area.',
  },
  {
    'order': '8',
    'question': 'I\'m too drunk to see, but I don\'t feel good.',
    'image': 'asset/images/alcol.png',
    'ans_a': 'Let\'s go to bed first. The shower room isn\'t a bad place either.',
    'ans_b': 'Look for a plastic bag.',
  },
  {
    'order': '9',
    'question': 'The delicious kimbap has cooled down. I should wrap it in "Eunbakji" and eat it.',
    // 'image': 'assets/images/image9.png',
    'ans_a': 'Put it in a microwave-safe container and go to do laundry.',
    'ans_b': 'Put it in a microwave-safe container and heat it up.',
  },
  {
    'order': '10',
    'question': 'I love Gyoza so much I have to eat it three times a week. Otherwise, I don\'t think I\'ll make it through this semester. But delivery is too expensive.',
    // 'image': 'assets/images/image10.png',
    'ans_a': 'I have to bring an air fryer! Hehe if I don\'t get caught, it\'s fine.',
    'ans_b': 'Choose to become a Gyoza master after taking a leave of absence.',
  },
  {
    'order': '11',
    'question': 'The sink is full of food scraps! The water doesn\'t drain well either.',
    // 'image': 'assets/images/image11.png',
    'ans_a': 'Wouldn\'t it be okay to throw away a bit more..? Dispose of the remaining scraps.',
    'ans_b': 'Empty the food waste strainer!',
  },
];
