// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_GXtjnqqNkuXigvPX-JEp4HTIHIou3sc',
    appId: '1:1034875227938:web:1dcf27870b40dd28fa5f7b',
    messagingSenderId: '1034875227938',
    projectId: 'hcidb-b30b6',
    authDomain: 'hcidb-b30b6.firebaseapp.com',
    storageBucket: 'hcidb-b30b6.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfu7Sph1dBk6PvdQnGbwOSaYlq3p5IItI',
    appId: '1:1034875227938:android:bcbeb622e02cba1cfa5f7b',
    messagingSenderId: '1034875227938',
    projectId: 'hcidb-b30b6',
    storageBucket: 'hcidb-b30b6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIGOFErjC20eaNEydsC3_1e3c7lqhie_U',
    appId: '1:1034875227938:ios:d4b0046e1a294f6dfa5f7b',
    messagingSenderId: '1034875227938',
    projectId: 'hcidb-b30b6',
    storageBucket: 'hcidb-b30b6.appspot.com',
    iosBundleId: 'com.example.mbtiology',
  );
}
