List<Map<String, String>> mbti_qs = [
  {
    'order': '1',
    'question': 'I am about to enter the dormitory. A person in front of me opens the door. Should I follow the door opened by the kind person?',
    'image': "asset/images/antipass.png",
    'ans_a': 'Follow that person! Kind person!',
    'ans_b': 'You might get trapped in the dormitory. Tag as Anti-Pass.',
  },
  {
    'order': '2',
    'question': 'An interview sheet has been posted in the dormitory chatroom! My heart races at the thought of my first meeting with the advisor... Should I go?',
    'image': "asset/images/gan.png",
    'ans_a': 'I have plans to hang out with my freshman friends! I have too much to do. Let\'s not go!',
    'ans_b': 'What kind of person is the advisor? Let\'s go!',
  },
  {
    'order': '3',
    'question': 'The tuberculosis screening bus is coming next week! Do I really need to get the tuberculosis test?',
    'image': "asset/images/bus.png",
    'ans_a': 'You have to submit the tuberculosis test results every semester! Let\'s get tested.',
    'ans_b': 'It\'s too bothersome... I\'ll just not stay in the dormitory next semester.',
  },
  {
    'order': '4',
    'question': 'The air conditioner is only producing heat... It\'s a hot summer... How should I survive?',
    'image': "asset/images/aa.png",
    'ans_a': 'File a complaint with the student council for repairs.',
    'ans_b': 'I am the best engineering student! I can fix anything!',
  },
  {
    'order': '5',
    'question': 'Exciting! I am going to have a meal with that person! But there\'s no place to eat in the same dormitory?',
    'image': "asset/images/open.png",
    'ans_a': 'Bethel has an open kitchen.',
    'ans_b': 'Disguise that person and have a meal together on my floor.',
  },
  {
    'order': '6',
    'question': 'I want to have a meeting with the advisor... My roommate is so rude! Help me!',
    'image': "asset/images/roommate.png",
    'ans_a': 'Record your name on the interview sheet with the advisor and visit.',
    'ans_b': 'It\'s too much... I can\'t stand it! Knock on the advisor\'s office door directly.',
  },
  {
    'order': '7',
    'question': 'It\'s 10:30 PM now! There is a problem and I need to go to the office. Which office should I go to?',
    'image': "asset/images/ja.png",
    'ans_a': 'Night administration office.',
    'ans_b': 'Student council office.',
  },
  {
    'order': '8',
    'question': 'There\'s no place to go on a date with my opposite-sex friend. What should I do?',
    'image': "asset/images/3.5.png",
    'ans_a': 'Utilize the 3.5th floor for a good time.',
    'ans_b': 'Go out of the dormitory and take a walk around Handong!',
  },
  {
    'order': '9',
    'question': 'Due to family circumstances, I have to leave the dormitory early! Where should I get a refund?',
    'ans_a': 'Talk to the secretary, talk to RC.',
    'ans_b': 'Refund? What is it? Should I take it?',
  },
  {
    'order': '10',
    'question': 'Who are the advisors of Bethel dormitory?',
    'ans_a': 'Advisor Eunhye Jang / Advisor Daeyeon Cho',
    'ans_b': 'Advisor Doseong Choi / Advisor Xiaopeng Yang',
  },
];
